project:
  type: website
  output-dir: docs
resources:
  - CNAME

website:
  title: "Tyler J. Wallett"
  favicon: imgs/me.jpg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects/index.qmd
        text: Projects
      - href: research/index.qmd
        text: Publications
      - href: courses/index.qmd
        text: Courses
    # right:
    #   - href: cv.qmd
    #     text: CV
  page-footer:
    left: "© Tyler Wallett, 2025–."

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
