project:
  type: website
resources:
  - CNAME

website:
  title: "Tyler Wallett"
  favicon: imgs/me.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects/index.qmd
        text: Projects
      - href: research/index.qmd
        text: Research
      - href: courses/index.qmd
        text: Courses
  page-footer:
    left: "© Tyler Wallett, 2025–."

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
